/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst";

declare module "sst" {
	export interface Resource {
		hoiTangStack: {
			type: "sst.aws.Astro";
			url: string;
		};
	}
}
